var dares = [
     "Prank call a random phone number."
    ,"Let the person next to you text anyone from your phone."
    ,"Pick your favorite song and dance on the tabletop/outside/etc."
    ,"Go outside and sing your favorite nursery rhyme."
    ,"Imitate three people in the room while others guess who you are playing/"
    ,"Have a two minute conversation with an inanimate object."
    ,"Eat a portion of a condiment or other food that isn't meant to be eaten straight."
    ,"Ask a man to put on makeup."
    ,"Have a woman let someone put her makeup on while blindfolded."
    ,"Have someone walk up to a stranger and say a random silly phrase."
    ,"Sniff the breath of everyone in the room and say who has the worst."
    ,"Put your hair in a silly style such as a pony tail on the top of your head."
    ,"Give your best snort for the group."
    ,"Try to scratch your armpit with your big toe."
    ,"Peel a banana using your feet."
    ,"Use lipstick to write a funny phrase across your face and leave it there for a predetermined length of time (no more than one hour or the end of the game)."
    ,"Smell someone's feet for ten seconds."
    ,"Eat a pudding cup or other sloppy food without using your hands."
    ,"Bite into a lemon slice."
    ,"Act like a dog and fetch a few objects."
    ,"Pretend you are in bed having a nightmare."
    ,"Go outside or somewhere public and do the chicken dance"
    ,"Wear a lampshade for a hat for a predetermined length of time."
    ,"Act out a scene from your favorite movie."
    ,"Spend the next round sitting on someone's lap."
    ,"Go outside and sing a clip of your favorite Disney song at the top of your lungs."
    ,"Exchange shirts with the person next to you for the next round of questions."
    ,"Wear a funny hat on your head for the next three rounds of questions."
    ,"Drink a mystery brew concocted by the rest of the group. Make sure there is nothing harmful or dangerous in the concoction, and set a reasonable limit of sips the person must take to complete the dare."
    ,"Everything you say for the rest of the game has to rhyme."
    ,"Give someone in the group a piggyback ride around the room."
    ,"Pretend that you're swimming underwater for the next three rounds of questions."
    ,"Prank call someone you know (perhaps another girl in the group that couldn't make it that night)."
    ,"Set up a tea party between any of the stuffed animals in the house. Invite the girls in your group to come join."
    ,"Eat a mouthful of crackers and try to whistle."
    ,"If there is a pet at the event, have that person try and hold the pet for the rest of the night."
    ,"Repeat everything another player says for the next three rounds of the game."
    ,"Wear your pants backward for the rest of the game."
    ,"Ask the neighbors to borrow a cup of sugar."
    ,"Sing instead of speaking for the next two rounds of the game."
    ,"Post a YouTube video after singing a currently popular song."
    ,"Make up a rap about the person to your right."
    ,"Run around the room imitating a monkey."
    ,"Say the alphabet backwards in a British accent."
    ,"Crack an egg on your head."
    ,"Pick your favorite song and dance to it on a table."
    ,"Kiss a member of the same or opposite sex in this room."
    ,"Stand in the center of a restaurant and sing your favorite nursery rhyme."
    ,"Give someone in this room a lap dance."
    ,"Make a prank call to someone you like."
    ,"Pick a member in this room and lick his/her cheek."
    ,"Eat a raw egg."
    ,"Imitate any three people in this room, while the others guess who they are."
    ,"Have a two-minute-long conversation with a chair or a wall."
    ,"Walk up to a stranger and convince him/her you're an alien sent to transform him/her."
    ,"Call an unknown number and tell that person you know where the Chamber of Secrets is."
    ,"Call up a hotel and ask if they serve dinosaurs. Also mention other foods you'd like with the dinosaur."
    ,"Follow someone on the road till they freak out."
    ,"If you're a guy, carry a woman's bag for one minute on a main street."
    ,"If you're a girl, carry a board on a main street that says: Up for adoption! Call __."
    ,"Wear everything yellow for a day, from your clothes to your accessories."
    ,"Tell the bartender in a club that you're doing a documentary on bartending and take inputs from him for half an hour."
    ,"Go to a hospital and convince the doctor you can't hear a thing."
    ,"Write a love letter to an acquaintance and send it via a Facebook message. Don't revert for 2 days."
    ,"Look angrily at every person who greets you for a day."
    ,"Send someone you know a message that says: I know what you did last summer."
    ,"If you're a guy, apply sticker eyelashes to your bike/car for a day and tell people you love this new look."
    ,"Call a friend in the middle of the night and tell him you just saw a spaceship."
    ,"Sit on a street and beg till you collect a set amount of money."
    ,"For half an hour, stand on the road and pretend as if you're talking to someone when you actually aren't."
    ,"Every time someone calls you, instead of saying hello, say 'you're gonna die' and hang up."
    ,"If you're a guy, paint your nails pink for a day."
    ,"If you're a girl, sport a fake mustache for an entire day and tell people you just thought of doing something different."
    ,"Test drive an expensive car and pretend to suddenly go blind."
    ,"In a pub, tell someone you'll buy them a drink and if accepted, order for orange juice."
    ,"Take off another guests sock with your teeth."
    ,"Sing the theme song to your favourite childhood cartoon."
    ,"Put your finger in your ear and then pull it out and lick it."
    ,"Push you nose up and oink like a pig, sniffing the person to your right."
    ,"Peel a banana using your feet."
    ,"Name a famous person who looks like each party guest in the room."
    ,"Using Lipstick, write \"Funky Monkey\" on your forehead and leave it there for 1 hour."
    ,"Let the person to your left decide who you should give butterfly kisses to."
    ,"Hold an ice cube in your hand until it melts."
    ,"Eat a spoon full of mustard."
    ,"Draw a fake mustache on your face and leave it there for 1 hour."
    ,"Come up with a cutesy pet name for all the party guests."
    ,"Burp out your full name."
    ,"Bite into a lemon slice."
    ,"Act like a dog and fetch something nearby with your mouth and drop it on the lap of the guest sitting to your right."
    ,"Stuff 8 marshmallows in your mouth and sing - Twinkle, Twinkle Little Star."
    ,"Eat a mouth full of crackers and then try and whistle."
    ,"Go into the front yard and do the Chicken Dance for 1 minute - make sure you bark loudly."
    ,"Kiss the bottom of your bare feet."
    ,"Sit on the lap of the person to your left for the rest of the game."
    ,"Jump on one leg for 20 seconds with both hands on your head, while barking like a dog."
    ,"You must ask the group for permission to use the bathroom for the rest of the party."
    ,"Exchange a clothing item with the person to your right."
    ,"Take the person to your left for a piggy back ride around the room."
    ,"Have the person to your right, give you a new hair do which you have to wear for the rest of the party."
    ,"Circle around each person in the room 5 times each."
    ,"You must be silent for the rest of the party."
    ,"Make up a dance and then teach the group."
    ,"Name the seven dwarfs, if they can't they should sing the song out loud."
    ,"Pretend you are underwater for the next 10 minutes."
    ,"You must wear a blindfold for the rest of the party and the person to your right is your guide."
    ,"The person on your left gets to tickle you for 30 seconds."
    ,"Mimic the person to your right."
    ,"Find 3 stuffed toys and have a pretend tea party."
    ,"Paint all the toe nails of all the guests."
    ,"All the guests are to wrap you in toilet paper and take a photo."
    ,"Create a short poem about \"Wedgies\" and recite it to the group."
    ,"Pretend to read a page out of a diary of the person sitting to you left, telling everyone all the juicy details."
    ,"Have all the guests put on bright red lipstick they are then to kiss you either on your face, arms or legs.  You must leave it on for 1 hour."
    ,"Act like a monkey, peel a banana, eat it and stay in monkey mode till the end of the game. "
    ,"Put on a blindfold and slow dance with a player. See if you can guess who it is by touch alone."
    ,"Go to the kitchen and eat something that is not meant to be eaten alone (like chili powder, pepper, etc)."
    ,"You have to remain perfectly sill for one minute. Meanwhile another player is going to attempt to get you to move buy whatever means he/she can think of. "
    ,"Become the slave of another player of your choosing for 10 minutes."
    ,"Go to the bathroom and change, you must \"go commando\" for the rest of the game."
    ,"Touch your nose with your tongue. If you are unable to do this you must touch another players nose with your tongue."
    ,"Go outside and run around, while screaming \"I have lost my voice, please help me find it\"."
    ,"Name all seven of Snow White's dwarfs. Any you are unable to name in 30 seconds will be written on your arms, legs, belly or face by the other players."
    ,"Give a piggyback ride to or receive a piggyback ride from another player."
    ,"Call one person at random who you know and knows you ask them \"When a cow laughs, does milk come out it's nose?\""
    ,"Put an ice cube in your pants pocket and keep it there until it completely melts."
    ,"Have another player tie or tape your hands together for a minimum of the next three rounds. You must select a dare before you can be untied."
    ,"Put lipstick on another player but you are not allowed to use your hands."
    ,"Get on all four and howl and bark at another player anytime they move or speak for the next 3 rounds."
    ,"Have another player select a food from the kitchen for you to eat without the uses of your hands. (The messier the better.)"
    ,"Act out a TV commercial of your choosing. Enlist the help of other players as needed but you cannot tell which"
    ,"Pound your chest and do your best Tarzan yell."
    ,"Attach toilet paper to your shoe and keep it there for the rest of the game."
    ,"Poke someone you do not know on facebook"
    ,"Go to the neighbors and ask to borrow an umbrella"
    ,"Put on a blindfold and feel another players face, see if you can guess who it is buy touch alone."
    ,"Take an item of food from the refrigerator and kiss it passionately for 90 seconds."
    ,"Select another player and repeat everything they say for the next 3 rounds. "
    ,"Pick your nose and show the results to the group? "
    ,"Stand facing another player. Each player must reach out toward the other player and get as close as possible to the other player with out touching them. The player who first touches the other player must answer a penalty truth question."
    ,"Tuck in your shirt and drop an ice cube down your front. You must then perform a break dance until the ice cube shakes out or melts."
    ,"Take off your shoe and suck on one of your toes. If you are unable to suck on your own toe you must suck on another players toe. "
    ,"Record a video of you singing any popular song that you know all the words to and post it to youtube"
    ,"For the next person, who is not a player, that walks into the room give them a hug and refuse to let go. "
    ,"Sit astride another players back or lap and peddle as if riding a bicycle. Pantomime an entire Tour de France style bicycle race complete with hill assents, passing other players and a triumphant finish. The performance should last at least two minutes. "
    ,"Select another player and describe in detail what you would have them do if they were your slave for the next hour. What would you have them do? (The selected player must then accept or reject the offer to become your slave.) "
    ,"For the rest of the night begin everything you say with \"All hail Queen Nefertiti.\""
    ,"For the rest of the evening wear a bicycle helmet. If a helmet is unavailable enlist the other players to help you fashion one out of cardboard, foil or whatever is available. "
    ,"Login to your favorite video game and allow another player to do whatever that what with you account for 3 minutes. "
    ,"Place both your hands in another players pockets and keep them there for 15 minutes. You must each perform a dare before you are allowed to remove them. "
    ,"Have another player tie you ankles together and keep them tied for 10 minutes. "
    ,"Update your facebook or other social media status to read looking to engage the services of a professional matchmaker. "
    ,"Go outside and dance like a cowboy.  "
    ,"Go outside with a sign that says \"Dance for me if you think I'm cute!\" "
    ,"Pose like your favorite model. "
    ,"Do a model runway walk outside on the sidewalk. "
    ,"Sit on the lap of the person on your right for the rest of the game!"
    ,"Pour a cup of ice cold or hot water on yourself outside"
    ,"Stand outside with a sign that says \"Honk if I'm Cute!\""
    ,"Jump on one leg for 20 seconds with both hands on your head."
    ,"Dance Crazy"
    ,"Run around wearing socks on your hands, pants for a shirt and a shirt for pant for 3 minutes."
    ,"Call your crush and sing \"I can't help falling in love with you\" to him. "
    ,"Stand in you front yard, wave and say 'Hi!' to everyone you see. "
    ,"Call your crush and explain the rules of monopoly to him."
    ,"Try licking your elbow while singing the alphabet"
    ,"Wrap yourself up in toilet paper and take a picture."
    ,"Prank call your crush and sing .. \" I can't help falling in love with you\"."
    ,"Go outside and check the mailbox."
    ,"You must ask the group for permission to use the bathroom for the rest of the night."
    ,"Exchange a clothing item with the person on your right."
    ,"Whenever someone says \"like\" you must say \" there you go again\" for the next hour."
    ,"Dance crazy with no music."
    ,"For the duration of the game you must yell out exclamations randomly."
    ,"Take the person on your right on a piggy back ride around the room."
    ,"Go outside and tell the first person you see that you like/love/hate them."
    ,"Have the person on your right do your hair any way they want and you have to keep it like that for the rest of the game."
    ,"Say \"hippity hop\" after anything you or anyone says for the next 10 minutes."
    ,"Circle around each person in the room 5 times each."
    ,"Everything you say for the next 15 minutes must be sung to the tune of \"Happy Birthday\". "
    ,"Dance around the room singing a Hannah Montana song chosen by the person on your right."
    ,"Smell the feet of everyone in the room and rank them from best to worst."
    ,"Sing \"I love you, you love me\" from Barney with all the motions."
    ,"Prank call your crush and ask his favorite color."
    ,"Skip down the street singing \"Mary had a little lamb\"."
    ,"Say the pledge of allegiance in your most un-favorite teachers voice."
    ,"Eat a teaspoon of either mustard, soy sauce or hot sauce."
    ,"Eat a bite out of a sandwich made from each person choosing one ingredient to put on the sandwich."
    ,"Have the person to the left of you do your makeup ... blindfolded."
    ,"Stand on your head for 1 minute."
    ,"Find 3 stuffed animals and have a pretend tea party orbirthday party."
    ,"Make up a new dance and teach it to the group."
    ,"Run down the street in your pj's"
    ,"Ask a neighbor for a roll of toilet paper."
    ,"Show everything that is in your purse."
    ,"Read the last note you received out loud."
    ,"Call Walmart and ask if you can use their dressing room to try on a pair of jeans you received as a gift."
    ,"Have the group paint your fingernails any way they want to."
    ,"Whenever anyone says \"like\" you have to say \"honk honk\" for the next 30 minutes."
    ,"Play \"This little piggy went to market\" on everyone's toes."
    ,"Go to the hosts and say \"thank you for a lovely time\"."
    ,"Pretend hosts dog (pet) is your crush and ask him out on a date."
    ,"Name the seven dwarfs."
    ,"Go outside with a sign that says \"I'm a Dork\"."
    ,"Prank call your Mom."
    ,"Wrap yourself up as a birthday party present."
    ,"Chug a soda in 10 seconds."
    ,"Mimic your friend and her boyfriend."
    ,"Pretend to be the person on your right for 10 minutes."
    ,"Eat a mouthful of crackers and then try and whistle."
    ,"Pretend that you are underwater for the next 10 minutes."
    ,"Take a balloon outside and try and set it free. "
    ,"Text everyone you know and say \"I rock!\""
    ,"Call your brother or sister and tell them how great they are."
    ,"Do your best ballet dance."
    ,"Build a tower out of anything you can find until it is taller then you are."
    ,"After everything you say add \"Whoa ... I'm good!\" for the next 15 minutes."
    ,"Do 20 cartwheels in a row"
];

var default_names = [
    "Slug"
   ,"Maggot"
   ,"Dufus"
   ,"Toad"
   ,"Worms"
   ,"Scum"
   ,"Tool"
   ,"Chicken"
   ,"Mutt"
   ,"Troll"
   ,"Squid"
   ,"Pansy"
   ,"Dopey"
   ,"Git"
   ,"Nutter"
   ,"Pig"
   ,"Twit"
   ,"Twirp"
   ,"Wimp"
   ,"Cupcake"
   
   ,"Crib Lizard"
   ,"Bratleigh"
   ,"Rug Rat"
   ,"House Ape"
   ,"Yard Monkey"
   ,"Ankle Biter"
   ,"Spawn"
   ,"Larvae"
   ,"Mini-me"
   ,"Oops"
   ,"Litter"
   ,"Crayon Gobbler"
   ,"Creepy Crawler"
   ,"Munchkin"
   ,"Shriekling"
   ,"Floor Monster"
   ,"Bratzilla"
   ,"Linoleum Lizard"
   ,"Flesh Loaf"
   ,"Snot Monster"
   ,"Crumb Cruncher"
];